### PR TITLE
Add mechanism for compiling perl libs & perl libs for Solaris

### PR DESCRIPTION
**Pull request by chincheta0815**
Hi Philippe,

I added missing Solaris/OmniOS perl libraries.

For creating these I also create a new subfolder 'perl5lib' containing the needed sources plus a 'buildme.sh' file. The file is a reduced version of the official 'buildme.sh' in Logitech's 'slimserver-vendor.git' for creating the perl deps. 
Usage is e.g.: ./buildme.sh -i <pathToThePluginsLibDir> -p <pathToPerlBinary>

I would be glad if you could accept the request and add the files to your plugin.

COMMENTS:
What I could not figure out: Why are you also providing a 'Net::hostent'? This should be provided in the perl base package. If it is needed I will add it, just tell me. 

Another thing: It seems to me that the structure inside the lib-dir is not yet that much LMS conformal. Usually all platform & version independent perl files are located in the <baseDir>, versioned ones in <baseDir>/5.<perlMinorVersion> and architecture dependent ones in <baseDir>/5.<perlMinorVersion>/<arch>.
Maybe there would be a way to make that more conformal & standardized, reducing the rsync complexity in the buildme.sh script (This is really crappy). This would then allow a re-usage for your other plugins. The thing is that the structure of the lib-dir should be completely changed than. I can help there if you want me too. As for know the plugin at least works ;o)

### CODE REVIEW

**Comment by philippe44** [comment]
It's organized like that because it saves a ton of copies of the same files and perl/LMS find the common files at the root, above all the 5.x. They are the same across all 5.x. Otherwise I would have to have a copy under each 5.x directory and that a pain knowing that, as it is a very infrequent problem? In build that manually 
Re hostent, I can't remember on the top of my head, but there was a reason. Either it was missing on some platform (maybe Windows 5.14) or it was modified, but it was here for a purpose

**Comment by chincheta0815** [comment]
Ah. Okay. Thank's for the comment.
Concerning the copying I thought that it might be some issue ;o)
Concerning the frequency of the problem I can't tell anything. I just thought if there could occur some kind of an issue.

What I just did: I downloaded the lib-source-files from cpan.org, added them to the repo and wrote a routine. This enables one to use the perlbin provided by the system or a custom one. So adding libs for a new perl version would just mean: run the buildme.sh without doing cpan download or any other manual stuff.

I added some missing files for the rsync routine in the buildme.sh. I also added these files to the lib directory. Then there was also a cleanup as I commited the build folder.

**Comment by philippe44** [comment]
I was reveiwing the changes, thanks but it contains way too much data for what I think I need, and it's very 5.24 specific, seems to me. All I want for these libraries are the binaries that I can add to my "distribution", I don't want to add too many around them, sorry

**Comment by chincheta0815** [comment]
Of course it's your distro. I will be happy if you can add the 5.24 binaries and the *.ix & *.al files which are also needed.

How do you want me to change the pull request then? I will do that. Or are you maybe willing to add the perl5bin folder with a remark "unsupported by philippe44 but by me" then I could always keep it up to date and send you a pull request and other could also built bins for their systems. Otherwise some pieces for building are in a different repo making it maybe chaotic (sorry I do not have any other word there). This all has to be run only once not always when you build...

Sorry, but after all I have to clarify something which is maybe confusing in the script: All in there are only the plain binary packages, their dependencies and it will work with each and every perl. The hints-folder and the complexity of the script came together just because I used the official LMS script for the binary as this would be easier to maintain/upgrade in the future...

But anyway: it would be great to have the necessary *.so, *.ix, *.al files added. Just tell me the changes you prefer.

**Comment by chincheta0815** [comment]
Well, after a short time of thinking I created a new repo (https://github.com/chincheta0815/slimverver-plugins-vendor.git). It would be great if you try it out.

This way you won't be bothered and I can create the libs needed and create pull request...

**Comment by philippe44** [comment]
I've added 5.24 for your platform. Don't take it wrong, thanks for doing that and I'll look at the scripts, I just have a lot in my plate currently :-)

**Comment by chincheta0815** [comment]
No problem at all. I totally understand you.
This pull-request was really a mess. I think New Year Eve gave me the rest... I also messed up a version number of Bignum making it even more complex. In parallel to you adding my platform I reorganized the stuff also matching the lib versions you used. The latest pull request I did just adds to the platform-directory nowhere else (*.so, *..ix and *.al files).This allows staying with the same version of the modules keeping complexity as low as possible. I will keep it open so you can check once in a while...

Your new version should work anyway. That is all what is important.

Thanks again and sorry for this mess I created...

**Pull request closed without merging**
